# Generated by Django 2.2.1 on 2019-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='mess_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
