# Generated by Django 2.2.1 on 2019-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190615_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('BARODA', 'BARODA'), ('AHEMDAVAD', 'AHEMDAVAD'), ('VIDHYANAGAR', 'VIDHYANAGAR')], default='VADODARA', max_length=40),
        ),
    ]
