# Generated by Django 2.2.1 on 2019-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190615_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('VADODARA', 'VADODARA'), ('AHEMDAVAD', 'AHEMDAVAD'), ('VIDHYANAGAR', 'VIDHYANAGAR')], default='VADODARA', max_length=40),
        ),
    ]
