# Generated by Django 2.2.1 on 2019-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190624_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('390002', 'Fateganj'), ('390024', 'Nizampura')], default='Fateganj', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mess_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
