# Generated by Django 2.2.1 on 2019-08-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190829_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('Fateganj', 'Fateganj'), ('Nizampura', 'Nizampura')], default='Fateganj', max_length=40),
        ),
    ]
