# Generated by Django 2.2.1 on 2019-08-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190829_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('Fateganj', 'Fateganj'), ('Nizampura', 'Nizampura'), ('MS campus', 'MS campus'), ('Sama', 'Sama'), ('Amitnagar', 'Amitnagar'), ('MS girls campus', 'MS girls campus')], default='Fateganj', max_length=40),
        ),
    ]
