# Generated by Django 2.2.1 on 2019-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190829_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(choices=[('Fateganj', 'Fateganj'), ('Nizampura', 'Nizampura'), ('Waghodia road', 'Waghodia road'), ('MS campus', 'MS campus'), ('Sama', 'Sama'), ('Amitnagar', 'Amitnagar'), ('MS girls campus', 'MS girls campus')], default='Fateganj', max_length=40),
        ),
    ]
