# Generated by Django 2.2.1 on 2019-12-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.CharField(default='zone-1', max_length=40),
        ),
    ]
