# Generated by Django 2.2.1 on 2019-12-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zone',
            field=models.CharField(choices=[('zone-1', 'zone-1'), ('zone-2', 'zone-2'), ('zone-3', 'zone-3')], default='zone-1', max_length=40),
        ),
    ]
