# Generated by Django 2.2.1 on 2019-12-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_comp',
            field=models.BooleanField(default=True),
        ),
    ]
