# Generated by Django 2.2.1 on 2019-05-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190515_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='menu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
