# Generated by Django 2.2.1 on 2019-05-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190515_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.TextField(max_length=150),
        ),
    ]
