# Generated by Django 2.2.1 on 2019-06-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190604_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session',
            field=models.CharField(default='old', max_length=10),
        ),
    ]
