# Generated by Django 2.2.1 on 2019-06-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='session',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
