# Generated by Django 2.2.1 on 2019-06-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190615_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='VADODARA', max_length=40),
        ),
    ]
