# Generated by Django 2.2.1 on 2019-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190909_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.TextField(max_length=350),
        ),
    ]
